#!/bin/sh

curl -s https://core.telegram.org/getProxySecret -o /var/lib/mtproxy/proxy-secret
curl -s https://core.telegram.org/getProxyConfig -o /var/lib/mtproxy/proxy-multi.conf

chown mtproxy:root /var/lib/mtproxy/proxy-secret /var/lib/mtproxy/proxy-multi.conf
chmod 0400 /var/lib/mtproxy/proxy-secret /var/lib/mtproxy/proxy-multi.conf